version: "3.7"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./my_conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    redis:
      image: "redis:latest"
      volumes:
        - redis-data:/data
      ports:
        - 6379:6379

    adminer:
      image: adminer
      restart: always
      ports:
        - 9001:8080

  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   # restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: password

  nginx:
    image: nginx:stable-alpine
    # container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
